Repository pelican-dev/panel, pull requests merged in 2025-02, with the labels that each got.

#961 Filter out wings `metadata` in `ListActivities`
  app/Filament/Server/Resources/ActivityResource/Pages/ListActivities.php
Labels: 🐛 bug

#968 Add back TransientToken check
  app/Http/Requests/Api/Application/ApplicationApiRequest.php
Labels: 🐛 bug

#972 Add default import `url` on `EditEgg`
  app/Filament/Components/Actions/ImportEggAction.php
Labels: ✨ feature

#975 Fix `OAuthProvider` & Add `ColorPicker` for `Authentik`
  .gitignore
  app/Extensions/OAuth/Providers/AuthentikProvider.php
  app/Extensions/OAuth/Providers/DiscordProvider.php
  app/Filament/Pages/Auth/EditProfile.php
Labels: 🐛 bug, ✨ feature

#977 Fix `ServerList` `Filter` query
  app/Filament/App/Resources/ServerResource/Pages/ListServers.php
Labels: 🐛 bug

#990 Fix `Setting` Saved `Translation`
  lang/en/admin/setting.php
Labels: 🐛 bug

#991 Fix `Admin Area` `translations`
  app/Checks/NodeVersionsCheck.php
  app/Console/Commands/User/DisableTwoFactorCommand.php
  app/Filament/Admin/Resources/NodeResource/RelationManagers/AllocationsRelationManager.php
  app/Filament/Admin/Resources/ServerResource/Pages/CreateServer.php
  app/Filament/Admin/Resources/ServerResource/RelationManagers/AllocationsRelationManager.php
  app/Filament/Admin/Resources/WebhookResource/Pages/CreateWebhookConfiguration.php
  app/Filament/Pages/Auth/EditProfile.php
  app/Filament/Server/Resources/UserResource.php
  app/Filament/Server/Resources/UserResource/Pages/ListUsers.php
  app/Services/Servers/ToggleInstallService.php
  lang/en/admin/databasehost.php
  lang/en/admin/node.php
  lang/en/admin/server.php
  lang/en/exceptions.php
Labels: 🐛 bug

#999 Fix `Health` `ScheduleCheck`
  app/Checks/ScheduleCheck.php
Labels: 🐛 bug

#994 Fix `Translations`
  app/Console/Commands/Environment/DatabaseSettingsCommand.php
  app/Console/Commands/Node/MakeNodeCommand.php
  app/Console/Commands/Node/NodeConfigurationCommand.php
  app/Console/Commands/Overrides/KeyGenerateCommand.php
  app/Console/Commands/Schedule/ProcessRunnableCommand.php
  app/Console/Commands/UpgradeCommand.php
  app/Filament/Admin/Resources/NodeResource/RelationManagers/AllocationsRelationManager.php
  app/Filament/Admin/Resources/ServerResource/Pages/EditServer.php
  app/Filament/Admin/Resources/UserResource/RelationManagers/ServersRelationManager.php
  app/Filament/Pages/Auth/Login.php
  app/Filament/Server/Resources/ActivityResource/Pages/ListActivities.php
  app/Http/Controllers/Api/Application/Mounts/MountController.php
  app/Models/User.php
  app/Services/Nodes/NodeDeletionService.php
  app/Traits/Commands/RequestRedisSettingsTrait.php
  lang/en/exceptions.php
Labels: 🐛 bug

#1001 Add `WordWrap` to `MonacoEditor`
  resources/views/filament/plugins/monaco-editor.blade.php
Labels: ✨ feature

#995 Fix incorrect `Allocation` permission in Node's `AllocationsRelationManager`
  app/Filament/Admin/Resources/NodeResource/RelationManagers/AllocationsRelationManager.php
Labels: 🐛 bug

#1004 Add `ignoreRecord: true` to `Server` ExternalId
  app/Filament/Admin/Resources/ServerResource/Pages/CreateServer.php
  app/Filament/Admin/Resources/ServerResource/Pages/EditServer.php
Labels: 🐛 bug

#1008 Add missing `selectablePlaceholder(false)` & `native(false)` Fix 500
  app/Filament/Admin/Pages/Settings.php
  app/Filament/Admin/Resources/ServerResource/Pages/CreateServer.php
  app/Filament/Pages/Auth/EditProfile.php
  app/Filament/Server/Resources/ScheduleResource.php
Labels: 🐛 bug

#952 Fix `File Upload`
  app/Filament/Admin/Resources/NodeResource/Pages/CreateNode.php
  app/Filament/Admin/Resources/NodeResource/Pages/EditNode.php
  app/Filament/Server/Resources/FileResource/Pages/ListFiles.php
  app/Repositories/Daemon/DaemonFileRepository.php
  lang/en/admin/node.php
Labels: 🐛 bug

#1010 Fix deleted users being shown as "System" in activity log
  app/Filament/Server/Resources/ActivityResource/Pages/ListActivities.php
  app/Models/ActivityLog.php
Labels: 🐛 bug

#993 fix(docker): enable multi-arch builds
  .github/workflows/docker-publish.yml
  Dockerfile
  Dockerfile.base
Labels: 🐛 bug

#1009 Interpret `Server` `StartupCommand` variables
  app/Filament/Admin/Resources/ServerResource/Pages/EditServer.php
  app/Filament/Components/Forms/Actions/PreviewStartupAction.php
  app/Filament/Server/Pages/Startup.php
Labels: ✨ feature

#1013 Add `Egg` `copy from` & `ReplicateAction`
  app/Filament/Admin/Resources/EggResource/Pages/CreateEgg.php
  app/Filament/Admin/Resources/EggResource/Pages/EditEgg.php
  app/Filament/Admin/Resources/EggResource/Pages/ListEggs.php
  app/Filament/Components/Forms/Fields/CopyFrom.php
  resources/views/filament/plugins/monaco-editor.blade.php
Labels: ✨ feature

#1014 Add backend validation to subuser permissions
  app/Services/Subusers/SubuserCreationService.php
  app/Services/Subusers/SubuserUpdateService.php
Labels: 🐛 bug

#1019 Fix `Node` Edit Page
  app/Filament/Admin/Resources/NodeResource/Pages/CreateNode.php
  app/Filament/Admin/Resources/NodeResource/Pages/EditNode.php
  app/Filament/Admin/Resources/ServerResource/Pages/CreateServer.php
  app/Filament/Admin/Resources/ServerResource/Pages/EditServer.php
Labels: 🐛 bug

#1026 Add missing `Egg` `RESERVED_ENV_NAMES`
  app/Models/EggVariable.php
Labels: 🐛 bug

#1015 Don't log duplicated `OauthProvider`s during tests
  app/Extensions/OAuth/Providers/AuthentikProvider.php
  app/Extensions/OAuth/Providers/CommonProvider.php
  app/Extensions/OAuth/Providers/DiscordProvider.php
  app/Extensions/OAuth/Providers/GithubProvider.php
  app/Extensions/OAuth/Providers/OAuthProvider.php
  app/Extensions/OAuth/Providers/SteamProvider.php
  app/Providers/AppServiceProvider.php
Labels: 🐛 bug
