Repository pelican-dev/panel, pull requests merged in 2025-03, with the labels that each got.

#1042 Use `BuildModificationService` on `EditServer`
  app/Filament/Admin/Resources/NodeResource/Pages/EditNode.php
  app/Filament/Admin/Resources/ServerResource/Pages/EditServer.php
  app/Services/Servers/BuildModificationService.php
  lang/en/admin/node.php
  lang/en/admin/server.php
Labels: 🐛 bug

#1053 Fix `EditServer` saving only Build infos
  app/Filament/Admin/Resources/ServerResource/Pages/EditServer.php
  app/Services/Servers/BuildModificationService.php
Labels: 🐛 bug

#1049 Add missing `Database` address field
  app/Filament/Admin/Resources/ServerResource/Pages/EditServer.php
  app/Filament/Server/Resources/DatabaseResource/Pages/ListDatabases.php
  app/Models/Database.php
  lang/en/admin/databasehost.php
Labels: ✨ feature

#1067 Fix Build UI Tests running twice
  .github/workflows/build.yaml
Labels: 🐛 bug

#1072 Tests: Make `PHPstan` run in 8.2, 8.3 & 8.4
  .github/workflows/lint.yaml
  app/Extensions/Backups/BackupManager.php
  app/Livewire/AlertBannerContainer.php
Labels: 🐛 bug

#1078 Fix missing space in `OAuth` modal
  app/Filament/Admin/Pages/Settings.php
Labels: 🐛 bug

#1083 `Server` Model does not use `SoftDelete`
  app/Models/Server.php
Labels: 🐛 bug

#1080 Fix `FindViableNodeService` to actually filter `Tags`
  app/Services/Deployment/FindViableNodesService.php
Labels: 🐛 bug

#1075 Fix null `Node` `Stats`
  app/Models/Node.php
Labels: 🐛 bug

#1086 Silent `file_exists` when its not allowed in `open_basedir`
  app/Console/Commands/Environment/QueueWorkerServiceCommand.php
  app/Livewire/Installer/Steps/QueueStep.php
Labels: 🐛 bug

#987 Fix revamp api_keys migration
  app/Models/ApiKey.php
  database/migrations/2024_11_04_185326_revamp_api_keys_permissions.php
Labels: 🐛 bug

#1071 Add url `Repeater` to `ImportEggHeaderAction`
  app/Filament/Admin/Resources/EggResource/Pages/EditEgg.php
  app/Filament/Admin/Resources/EggResource/Pages/ListEggs.php
  app/Filament/Components/Actions/ImportEggAction.php
  app/Filament/Components/Tables/Actions/ImportEggAction.php
  lang/en/admin/egg.php
Labels: ✨ feature

#1082 Laravel 12.2.0 Shift
  composer.json
  composer.lock
Labels: dependencies

#1101 Use `ContainerStatus::tryFrom` in `ProcessScheduleService`
  app/Services/Schedules/ProcessScheduleService.php
Labels: 🐛 bug

#1102 Hide `Directory` size in `ListFiles`
  app/Filament/Server/Resources/FileResource/Pages/ListFiles.php
Labels: 🐛 bug

#1109 Fix `DaemonFileRepository` in `ListFiles`
  app/Filament/Server/Resources/FileResource/Pages/ListFiles.php
Labels: 🐛 bug

#1111 Add `header`, `footer` & `body-end` views
  app/Providers/AppServiceProvider.php
  resources/views/filament/layouts/body-end.blade.php
  resources/views/filament/layouts/footer.blade.php
  resources/views/filament/layouts/header.blade.php
Labels: ✨ feature

#1104 Add App Logo
  app/Filament/Admin/Pages/Settings.php
  config/app.php
  lang/en/admin/setting.php
Labels: ✨ feature

#1110 Fix `ImportEggAction`
  app/Filament/Components/Actions/ImportEggAction.php
  app/Filament/Components/Tables/Actions/ImportEggAction.php
Labels: 🐛 bug

#1125 Add `tags` to egg importer & exporter, add tags to egg jsons
  app/Models/Egg.php
  app/Models/Node.php
  app/Services/Eggs/Sharing/EggExporterService.php
  app/Services/Eggs/Sharing/EggImporterService.php
  database/Seeders/eggs/minecraft/egg-bungeecord.json
  database/Seeders/eggs/minecraft/egg-forge-minecraft.json
  database/Seeders/eggs/minecraft/egg-paper.json
  database/Seeders/eggs/minecraft/egg-sponge--sponge-vanilla.json
  database/Seeders/eggs/minecraft/egg-vanilla-minecraft.json
  database/Seeders/eggs/rust/egg-rust.json
  database/Seeders/eggs/source-engine/egg-counter--strike--global-offensive.json
  database/Seeders/eggs/source-engine/egg-custom-source-engine-game.json
  database/Seeders/eggs/source-engine/egg-garrys-mod.json
  database/Seeders/eggs/source-engine/egg-insurgency.json
  database/Seeders/eggs/source-engine/egg-team-fortress2.json
  database/Seeders/eggs/voice-servers/egg-mumble-server.json
  database/Seeders/eggs/voice-servers/egg-teamspeak3-server.json
Labels: ✨ feature

#1124 Add tag filter to lists
  app/Filament/Admin/Resources/EggResource/Pages/ListEggs.php
  app/Filament/Admin/Resources/NodeResource/Pages/ListNodes.php
  app/Filament/Components/Tables/Filters/TagsFilter.php
Labels: ✨ feature

#1116 Fix path resolving when moving files
  app/Filament/Server/Resources/FileResource/Pages/ListFiles.php
  lang/en/activity.php
Labels: 🐛 bug

#1122 Add update egg bulk action
  app/Filament/Admin/Resources/EggResource/Pages/ListEggs.php
  app/Filament/Components/Tables/Actions/UpdateEggAction.php
  app/Filament/Components/Tables/Actions/UpdateEggBulkAction.php
  lang/en/admin/egg.php
Labels: ✨ feature

#1129 Catch `DaemonFileRepository` & show Alert
  app/Filament/Server/Resources/FileResource/Pages/ListFiles.php
  app/Models/File.php
Labels: 🐛 bug

#1106 Catch `NodeUpdateService` in `EditNode` & `NodeController`
  app/Filament/Admin/Resources/NodeResource/Pages/EditNode.php
  app/Http/Controllers/Api/Application/Nodes/NodeController.php
Labels: 🐛 bug

#1120 Fix SMTP scheme/ encryption
  app/Filament/Admin/Pages/Settings.php
  config/mail.php
  lang/en/admin/setting.php
Labels: 🐛 bug

#1142 Add host config to gitlab oauth (& add setup steps)
  app/Extensions/OAuth/Providers/GitlabProvider.php
  app/Providers/AppServiceProvider.php
Labels: ✨ feature
